apiVersion: v2
name: common
description: This is common chart for my home deployment
type: application
version: 1.0.2
appVersion: 1.16.0
dependencies:
- name: library
  repository: file://../library
  version: x.x.x