apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "library.names.name" . }}
  labels:
    {{- include "library.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  successfulJobsHistoryLimit: {{.Values.cronjob.successfulJobsHistoryLimit}}
  failedJobsHistoryLimit: {{.Values.cronjob.failedJobsHistoryLimit}}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "schedule-pod-restart.serviceAccountName" . }}
          containers:
          - name: kubectl-container
            image: bitnami/kubectl:{{ .Values.image.tagname }}
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            args:
            -  {{ range .Values.cronjob.podLabels }} kubectl delete pods -l {{ . }} --namespace={{$.Release.Namespace}}; {{- end }} 
          restartPolicy: OnFailure
