apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "motioneye.fullname" . }}
  labels:
    {{- include "motioneye.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "motioneye.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{.Values.deploymentStrategy.type }}
  template:
    metadata:
      labels:
        {{- include "motioneye.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "motioneye.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.env }}
          env:
          {{- range $key, $value := .Values.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ include "motioneye.imageTag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8765
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - mountPath: /etc/motioneye
              name: config
            {{- if .Values.persistence.config.subPath }}
              subPath: {{ .Values.persistence.config.subPath }}
            {{ end }}
            {{- if .Values.persistence.data.enabled }}
            - mountPath: /var/lib/motioneye
              name: data
            {{- if .Values.persistence.data.subPath }}
              subPath: {{ .Values.persistence.data.subPath }}
            {{ end }}
            {{ end }}
            {{- if .Values.additionalVolumeMounts }}
              {{- toYaml .Values.additionalVolumeMounts | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- if .Values.persistence.config.enabled }}
        - name: config
          persistentVolumeClaim:
        {{- if .Values.persistence.config.existingClaim }}
            claimName: "{{ .Values.persistence.config.existingClaim }}"
        {{- else }}
            claimName: {{ include "motioneye.configPVCName" . }}
        {{- end }}
        {{- else }}
        - name: config
          emptyDir: {}
        {{- end }}
        {{- if .Values.persistence.data.enabled }}
        - name: data
          persistentVolumeClaim:
        {{- if .Values.persistence.data.existingClaim }}
          claimName: "{{ .Values.persistence.data.existingClaim }}"
        {{- else }}
            claimName: {{ include "motioneye.dataPVCName" . }}
        {{- end }}
        {{- end }}
        {{- if .Values.additionalVolumes }}
          {{- toYaml .Values.additionalVolumes | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
