image:
  repository: vikaspogu/garage-opener
  pullPolicy: IfNotPresent
  tag: "sha-d1dd658"

env:
  ENVIRONMENT: prod
  MQTT_BROKER: vernemq.default.svc.cluster.local
  OPEN_PIN: "12"
  NOTIFICATION_TIME: "1800000"

serviceMonitor:
  enabled: false

probes:
  liveness:
    custom: true
    enabled: true
    spec:
      failureThreshold: 3
      httpGet:
        path: /health
        port: http
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 10

  readiness:
    custom: true
    enabled: true
    spec:
      failureThreshold: 3
      httpGet:
        path: /health
        port: http
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 10
      
  startup:
    enabled: false

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/auth-url: "https://auth.homenet.vikaspogu.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.homenet.vikaspogu.com/oauth2/start?rd=https%3A%2F%2F$host$request_uri"
  hosts:
    - host: garage-opener.homenet.vikaspogu.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: garage-opener-tls
      hosts:
        - garage-opener.homenet.vikaspogu.com

additionalVolumes:
  - name: dev-gpiomem
    hostPath:
      path: /dev/gpiomem

additionalVolumeMounts:
  - mountPath: /dev/gpiomem
    name: dev-gpiomem
