image:
  repository: harbor.homenet.vikaspogu.com/homelab/garage-opener
  pullPolicy: IfNotPresent
  tag: "sha256:f70e73fa"

imagePullSecrets:
  - name: harbor-registry-secret

env:
  ENVIRONMENT: prod
  MQTT_BROKER: vernemq.default.svc.cluster.local
  OPEN_PIN: "12"
  NOTIFICATION_TIME: "1800000"
envValueFrom:
  SLACK_WEBHOOK:
    secretKeyRef:
      key: SLACK_WEBHOOK
      name: garage-credentials

securityContext:
  privileged: true

serviceMonitor:
  enabled: true

probes:
  liveness:
    custom: true
    enabled: true
    spec:
      failureThreshold: 3
      httpGet:
        path: /health
        port: http
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 10

  readiness:
    custom: true
    enabled: true
    spec:
      failureThreshold: 3
      httpGet:
        path: /health
        port: http
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 10
      
  startup:
    enabled: false

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/auth-url: "https://auth.homenet.vikaspogu.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.homenet.vikaspogu.com/oauth2/start?rd=https%3A%2F%2F$host$request_uri"
  hosts:
    - host: garage-opener.homenet.vikaspogu.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: garage-opener-tls
      hosts:
        - garage-opener.homenet.vikaspogu.com
volumes:
  - name: dev-gpiomem
    hostPath:
      path: /dev/gpiomem
volumeMounts:
  - mountPath: /dev/gpiomem
    name: dev-gpiomem
resources:
  limits:
    cpu: 520m
    memory: 520Mi
  requests:
    cpu: 250m
    memory: 250Mi